# Generated by Django 3.2.8 on 2022-09-04 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20220810_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('desc', models.CharField(max_length=50)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('desc', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('amount', models.PositiveIntegerField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
