# Generated by Django 3.2.8 on 2022-09-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_categorie_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
